"""Add telegram id to User

Revision ID: 426fc6f5b528
Revises: 6547c7634d94
Create Date: 2025-06-21 10:06:48.181004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426fc6f5b528'
down_revision = '6547c7634d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('telegram_id')

    # ### end Alembic commands ###
