"""Upgrade

Revision ID: 6547c7634d94
Revises: 79bcf9139e3f
Create Date: 2025-06-16 23:40:28.357241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6547c7634d94'
down_revision = '79bcf9139e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('password'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('password'), ['password'], unique=True)

    # ### end Alembic commands ###
